"""First migration

Revision ID: 03851f794541
Revises: 
Create Date: 2023-04-06 11:19:10.942539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03851f794541'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_permission_group',
    sa.Column('group', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('group')
    )
    op.create_table('auth_user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('date_joined', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_auth_user_username'), 'auth_user', ['username'], unique=True)
    op.create_table('auth_permission',
    sa.Column('group', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['group'], ['auth_permission_group.group'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group', 'code')
    )
    op.create_table('auth_user_has_group',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('auth_group_has_permission',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('permission_group', sa.String(length=100), nullable=False),
    sa.Column('permission_code', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_group', 'permission_code'], ['auth_permission.group', 'auth_permission.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'permission_group', 'permission_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_group_has_permission')
    op.drop_table('auth_user_has_group')
    op.drop_table('auth_permission')
    op.drop_index(op.f('ix_auth_user_username'), table_name='auth_user')
    op.drop_table('auth_user')
    op.drop_table('auth_permission_group')
    op.drop_table('auth_group')
    # ### end Alembic commands ###
