version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    links:
      - mariadb
      - redis
      - mailpit

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      MARIADB_DATABASE: fastapi
  
  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - ./redis:/data

  redis-manager:
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      REDIS_HOSTS: redis

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
    links:
      - mariadb

  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    volumes:
      - ./mailpit:/data
    ports:
      - 8082:8025
      # - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1